const MODULE_NAMESPACE = 'settings'
const type = actionName => `${MODULE_NAMESPACE}/${actionName}`

export const FETCH_SETTINGS_REQUEST = type('FETCH_SETTINGS_REQUEST')
export const FETCH_SETTINGS_SUCCESS = type('FETCH_SETTINGS_SUCCESS')
export const FETCH_SETTINGS_FAIL = type('FETCH_SETTINGS_FAIL')

export const SAVE_SETTINGS_REQUEST = type('SAVE_SETTINGS_REQUEST')
export const SAVE_SETTINGS_SUCCESS = type('SAVE_SETTINGS_SUCCESS')
export const SAVE_SETTINGS_FAIL = type('SAVE_SETTINGS_FAIL')

export const CHANGE_SETTING = type('CHANGE_SETTING')
