import config from '../../config'
const MODULE_NAMESPACE = 'user'
const type = actionName => `${config.NAMESPACE}/${MODULE_NAMESPACE}/${actionName}`

export const FETCH_CURRENT_WEATHER_REQUEST = type('FETCH_CURRENT_WEATHER_REQUEST')
export const FETCH_CURRENT_WEATHER_SUCCESS = type('FETCH_CURRENT_WEATHER_SUCCESS')
export const FETCH_CURRENT_WEATHER_FAIL = type('FETCH_CURRENT_WEATHER_FAIL')

export const FETCH_DAILY_WEATHER_REQUEST = type('FETCH_DAILY_WEATHER_REQUEST')
export const FETCH_DAILY_WEATHER_SUCCESS = type('FETCH_DAILY_WEATHER_SUCCESS')
export const FETCH_DAILY_WEATHER_FAIL = type('FETCH_DAILY_WEATHER_FAIL')

export const FETCH_HOURLY_WEATHER_REQUEST = type('FETCH_HOURLY_WEATHER_REQUEST')
export const FETCH_HOURLY_WEATHER_SUCCESS = type('FETCH_HOURLY_WEATHER_SUCCESS')
export const FETCH_HOURLY_WEATHER_FAIL = type('FETCH_HOURLY_WEATHER_FAIL')

export const FETCH_WEATHER_FOR_SAVED_PLACES_REQUEST = type('FETCH_WEATHER_FOR_SAVED_PLACES_REQUEST')
export const FETCH_WEATHER_FOR_SAVED_PLACES_SUCCESS = type('FETCH_WEATHER_FOR_SAVED_PLACES_SUCCESS')
export const FETCH_WEATHER_FOR_SAVED_PLACES_FAIL = type('FETCH_WEATHER_FOR_SAVED_PLACES_FAIL')
