const MODULE_NAMESPACE = 'weather'
const type = actionName => `${MODULE_NAMESPACE}/${actionName}`

export const SET_WEATHER_VIEW = type('SET_WEATHER_VIEW')

export const FETCH_WEATHER_REQUEST = type('FETCH_WEATHER_REQUEST')
export const FETCH_WEATHER_SUCCESS = type('FETCH_WEATHER_SUCCESS')
export const FETCH_WEATHER_FAIL = type('FETCH_WEATHER_FAIL')

export const FETCH_HOURLY_FORECAST_REQUEST = type('FETCH_HOURLY_FORECAST_REQUEST')
export const FETCH_HOURLY_FORECAST_SUCCESS = type('FETCH_HOURLY_FORECAST_SUCCESS')
export const FETCH_HOURLY_FORECAST_FAIL = type('FETCH_HOURLY_FORECAST_FAIL')

export const WEATHER_FOR_SAVED_PLACES_REQUEST = type('WEATHER_FOR_SAVED_PLACES_REQUEST')
export const WEATHER_FOR_SAVED_PLACES_SUCCESS = type('WEATHER_FOR_SAVED_PLACES_SUCCESS')
export const WEATHER_FOR_SAVED_PLACES_FAIL = type('WEATHER_FOR_SAVED_PLACES_FAIL')

export const WEATHER_FOR_ACTIVE_PLACE_REQUEST = type('WEATHER_FOR_ACTIVE_PLACE_REQUEST')
export const WEATHER_FOR_ACTIVE_PLACE_SUCCESS = type('WEATHER_FOR_ACTIVE_PLACE_SUCCESS')
export const WEATHER_FOR_ACTIVE_PLACE_FAIL = type('WEATHER_FOR_ACTIVE_PLACE_FAIL')
