const MODULE_NAMESPACE = 'weather'
const type = actionName => `${MODULE_NAMESPACE}/${actionName}`

export const SET_WEATHER_VIEW = type('SET_WEATHER_VIEW')

export const FETCH_CURRENT_WEATHER_REQUEST = type('FETCH_CURRENT_WEATHER_REQUEST')
export const FETCH_CURRENT_WEATHER_SUCCESS = type('FETCH_CURRENT_WEATHER_SUCCESS')
export const FETCH_CURRENT_WEATHER_FAIL = type('FETCH_CURRENT_WEATHER_FAIL')

export const FETCH_DAILY_FORECAST_REQUEST = type('FETCH_DAILY_FORECAST_REQUEST')
export const FETCH_DAILY_FORECAST_SUCCESS = type('FETCH_DAILY_FORECAST_SUCCESS')
export const FETCH_DAILY_FORECAST_FAIL = type('FETCH_DAILY_FORECAST_FAIL')

export const FETCH_HOURLY_FORECAST_REQUEST = type('FETCH_HOURLY_FORECAST_REQUEST')
export const FETCH_HOURLY_FORECAST_SUCCESS = type('FETCH_HOURLY_FORECAST_SUCCESS')
export const FETCH_HOURLY_FORECAST_FAIL = type('FETCH_HOURLY_FORECAST_FAIL')
