const MODULE_NAMESPACE = 'savedPlaces'
const type = actionName => `${MODULE_NAMESPACE}/${actionName}`

export const FETCH_SAVED_PLACES_REQUEST = type('FETCH_SAVED_PLACES_REQUEST')
export const FETCH_SAVED_PLACES_SUCCESS = type('FETCH_SAVED_PLACES_SUCCESS')
export const FETCH_SAVED_PLACES_FAIL = type('FETCH_SAVED_PLACES_FAIL')

export const ADD_SAVED_PLACE_REQUEST = type('ADD_SAVED_PLACE_REQUEST')
export const ADD_SAVED_PLACE_SUCCESS = type('ADD_SAVED_PLACE_SUCCESS')
export const ADD_SAVED_PLACE_FAIL = type('ADD_SAVED_PLACE_FAIL')

export const REMOVE_SAVED_PLACE_REQUEST = type('REMOVE_SAVED_PLACE_REQUEST')
export const REMOVE_SAVED_PLACE_SUCCESS = type('REMOVE_SAVED_PLACE_SUCCESS')
export const REMOVE_SAVED_PLACE_FAIL = type('REMOVE_SAVED_PLACE_FAIL')
