import config from '../../config'
const MODULE_NAMESPACE = 'places'
const type = actionName => `${config.NAMESPACE}/${MODULE_NAMESPACE}/${actionName}`

export const OPEN_PLACES_MENU = type('OPEN_PLACES_MENU')
export const CLOSE_PLACES_MENU = type('CLOSE_PLACES_MENU')

export const SET_SEARCH_VALUE = type('SET_SEARCH_VALUE')
export const SET_ACTIVE_SUGGESTION = type('SET_ACTIVE_SUGGESTION')
export const RESET_SEARCH_BAR = type('RESET_SEARCH_BAR')

export const FETCH_SEARCH_SUGGESTIONS_REQUEST = type('FETCH_SEARCH_SUGGESTIONS_REQUEST')
export const FETCH_SEARCH_SUGGESTIONS_SUCCESS = type('FETCH_SEARCH_SUGGESTIONS_SUCCESS')
export const FETCH_SEARCH_SUGGESTIONS_FAIL = type('FETCH_SEARCH_SUGGESTIONS_FAIL')

export const FETCH_SAVED_PLACES_REQUEST = type('FETCH_SAVED_PLACES_REQUEST')
export const FETCH_SAVED_PLACES_SUCCESS = type('FETCH_SAVED_PLACES_SUCCESS')
export const FETCH_SAVED_PLACES_FAIL = type('FETCH_SAVED_PLACES_FAIL')

export const ADD_SAVED_PLACE_REQUEST = type('ADD_SAVED_PLACE_REQUEST')
export const ADD_SAVED_PLACE_SUCCESS = type('ADD_SAVED_PLACE_SUCCESS')
export const ADD_SAVED_PLACE_FAIL = type('ADD_SAVED_PLACE_FAIL')

export const REMOVE_SAVED_PLACE_REQUEST = type('REMOVE_SAVED_PLACE_REQUEST')
export const REMOVE_SAVED_PLACE_SUCCESS = type('REMOVE_SAVED_PLACE_SUCCESS')
export const REMOVE_SAVED_PLACE_FAIL = type('REMOVE_SAVED_PLACE_FAIL')

export const SET_ACTIVE_PLACE = type('SET_ACTIVE_PLACE')
