const MODULE_NAMESPACE = 'places'
const type = actionName => `${MODULE_NAMESPACE}/${actionName}`

export const SELECT_LOCATION = type('SELECT_LOCATION')
export const SET_ACTIVE_PLACE_ID = type('SET_ACTIVE_PLACE_ID')

export const FETCH_PLACE_DETAILS_REQUEST = type('FETCH_PLACE_DETAILS_REQUEST')
export const FETCH_PLACE_DETAILS_SUCCESS = type('FETCH_PLACE_DETAILS_SUCCESS')
export const FETCH_PLACE_DETAILS_FAIL = type('FETCH_PLACE_DETAILS_FAIL')
