const MODULE_NAMESPACE = 'places'
const type = actionName => `${MODULE_NAMESPACE}/${actionName}`

export const CLEAR_SEARCH_SUGGESTIONS = type('CLEAR_SEARCH_SUGGESTIONS')

export const FETCH_SEARCH_SUGGESTIONS_REQUEST = type('FETCH_SEARCH_SUGGESTIONS_REQUEST')
export const FETCH_SEARCH_SUGGESTIONS_SUCCESS = type('FETCH_SEARCH_SUGGESTIONS_SUCCESS')
export const FETCH_SEARCH_SUGGESTIONS_FAIL = type('FETCH_SEARCH_SUGGESTIONS_FAIL')

export const FETCH_SAVED_PLACES_REQUEST = type('FETCH_SAVED_PLACES_REQUEST')
export const FETCH_SAVED_PLACES_SUCCESS = type('FETCH_SAVED_PLACES_SUCCESS')
export const FETCH_SAVED_PLACES_FAIL = type('FETCH_SAVED_PLACES_FAIL')

export const ADD_SAVED_PLACE_REQUEST = type('ADD_SAVED_PLACE_REQUEST')
export const ADD_SAVED_PLACE_SUCCESS = type('ADD_SAVED_PLACE_SUCCESS')
export const ADD_SAVED_PLACE_FAIL = type('ADD_SAVED_PLACE_FAIL')

export const REMOVE_SAVED_PLACE_REQUEST = type('REMOVE_SAVED_PLACE_REQUEST')
export const REMOVE_SAVED_PLACE_SUCCESS = type('REMOVE_SAVED_PLACE_SUCCESS')
export const REMOVE_SAVED_PLACE_FAIL = type('REMOVE_SAVED_PLACE_FAIL')

export const SELECT_LOCATION = type('SELECT_LOCATION')
export const SET_ACTIVE_PLACE = type('SET_ACTIVE_PLACE')

export const FETCH_PLACE_DETAILS_REQUEST = type('FETCH_PLACE_DETAILS_REQUEST')
export const FETCH_PLACE_DETAILS_SUCCESS = type('FETCH_PLACE_DETAILS_SUCCESS')
export const FETCH_PLACE_DETAILS_FAIL = type('FETCH_PLACE_DETAILS_FAIL')
