const MODULE_NAMESPACE = 'searchbar'
const type = actionName => `${MODULE_NAMESPACE}/${actionName}`

export const CHANGE_INPUT_VALUE = type('CHANGE_INPUT_VALUE')
export const CLEAR_SEARCH_SUGGESTIONS = type('CLEAR_SEARCH_SUGGESTIONS')

export const FETCH_SEARCH_SUGGESTIONS_REQUEST = type('FETCH_SEARCH_SUGGESTIONS_REQUEST')
export const FETCH_SEARCH_SUGGESTIONS_SUCCESS = type('FETCH_SEARCH_SUGGESTIONS_SUCCESS')
export const FETCH_SEARCH_SUGGESTIONS_FAIL = type('FETCH_SEARCH_SUGGESTIONS_FAIL')
